"""Iterative eigendecomposition of curvature operators (Hessian, GGN, Fisher) for PyTorch models."""

from hessian_eigenthings.algorithms import (
    EigenResult,
    LanczosTridiag,
    SpectralDensityResult,
    TraceResult,
    deflated_power_iteration,
    hutch_plus_plus,
    hutchinson,
    lanczos,
    lanczos_tridiagonal,
    power_iteration_one,
    spectral_density,
    trace,
)
from hessian_eigenthings.loss_fns import (
    hf_lm_forward,
    hf_lm_loss,
    hf_lm_loss_of_output,
    hf_seq2seq_loss,
    supervised_forward,
    supervised_loss,
    supervised_loss_of_output,
    supervised_per_sample_loss,
    tlens_forward,
    tlens_loss,
    tlens_loss_of_output,
)
from hessian_eigenthings.operators import (
    CurvatureOperator,
    DDPHessianOperator,
    EmpiricalFisherOperator,
    GGNOperator,
    HessianOperator,
    LambdaOperator,
)
from hessian_eigenthings.param_utils import (
    ParamFilter,
    match_names,
    match_regex,
    params_to_vector,
    select_parameters,
    vector_to_params,
)

__version__ = "1.0.0a2"

__all__ = [
    "CurvatureOperator",
    "DDPHessianOperator",
    "EigenResult",
    "EmpiricalFisherOperator",
    "GGNOperator",
    "HessianOperator",
    "LambdaOperator",
    "LanczosTridiag",
    "ParamFilter",
    "SpectralDensityResult",
    "TraceResult",
    "deflated_power_iteration",
    "hf_lm_forward",
    "hf_lm_loss",
    "hf_lm_loss_of_output",
    "hf_seq2seq_loss",
    "hutch_plus_plus",
    "hutchinson",
    "lanczos",
    "lanczos_tridiagonal",
    "match_names",
    "match_regex",
    "params_to_vector",
    "power_iteration_one",
    "select_parameters",
    "spectral_density",
    "supervised_forward",
    "supervised_loss",
    "supervised_loss_of_output",
    "supervised_per_sample_loss",
    "tlens_forward",
    "tlens_loss",
    "tlens_loss_of_output",
    "trace",
    "vector_to_params",
    "__version__",
]
